version: '3.8'

services:
  postgres:
    container_name: axora-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: axora_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - axora-network
    restart: unless-stopped

  pgadmin:
    container_name: axora-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - axora-network
    restart: unless-stopped

networks:
  axora-network:
    driver: bridge

volumes:
  postgres_data: 